version: "3.7"

services:
  caddy:
    image: caddy
    container_name: caddy
    volumes:
      - ./.caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy-config:/config
      - caddy-data:/data
    ports:
      - 80:80
      - 443:443
    networks:
      - reverse-proxy
    restart: unless-stopped

volumes:
  caddy-config:
    name: caddy-config
  caddy-data:
    name: caddy-data

networks:
  reverse-proxy:
    name: reverse-proxy
