version: "3.7"

services:
  caddy:
    image: caddy
    container_name: caddy
    volumes:
      - ./.caddy/site:/usr/share/caddy
      - ./.caddy/data:/data
      - ./.caddy/config:/config
      - ./.caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
      - 443:443
    networks:
      - reverse-proxy
    restart: unless-stopped

networks:
  reverse-proxy:
    external: true
